# name used when creating Bank account in Craftconomy3
name: LowbrainBank

# allow player to sell damaged (used) item
allow_damaged_item: true

# if allow_damaged_item is set to true
# this will devalue the damaged item by the percentage of use
# like so : value = current_value / max_durability * durability
# so, if a item as 10 / 60 durability ( highly used ) and is worth 100 $, it will be sold @ 16.666 $
devalue_damaged_item: true

# profit determines the value at which the bank will buy an item.
# for example, if the value of diamond is at  500$, the bank will only pay players 450$ for it
# but players will pay full price.
# this can be set for any specifics items in bank-data.yml
# set to 0 to disable.
# default value = 0.10 = 10%
profit: 0.10

# time (seconds) to confirm and purchase or a sale
# using command => /lb econ confirm or cancel
# settings this value to zero or bellow will disable confirmation delay
# default value = 20
time_to_confirm: 20

# after the plugin is initialize for the first time, this value will be set automaticallly to false
# if you want to reset, set this value to true and restart the server / plugin
# you can also use the command => /lb econ reset
startup_reset: true

# the initial amount of currency in the bank at first initialisation
# this value will be use when first initializing the bank
# default value = 5000
initial_bank_balance: 5000

# current bank data
# used by the plugins
# default value = 5000 = to initial value
current_bank_balance: 5000

# minimum amount of currency in the bank
# players won't be able to sell items if the bank as not enough currency to buy the items
# settings this value bellow 0 will allow the bank be bankrupted
# default value = 0
min_bank_balance: 0

# maximum amount of currency the bank can hold
# players won't be able to buy items from the bank if it can't hold it
# settings this value bellow zero means the bank can hold infinite
# default value = -1
max_bank_balance: -1

# the price of an item is dropped every time a players sells one
# this value is used if it is not overriding in the bank-data.yml file for a specific item
# default value = 1
default_price_drop: 0.01

# the price of an item is increase every time a players buys one
# this value is used if it is not overriding in the bank-data.yml file for a specific item
# default value = 1
default_price_increase: 0.01

# this is the minimum time difference between the current time and the last time an item was bought before
# its start losing value
# for example, if an item hasn't been bought for a long time, its value will start decreasing
# this value can be overridden in the bank-data.yml file for a specific item
# this value is in minutes
# default value = 1440 (24 hours)
overtime_diff_drop: 1440

# this is the amount by which the value of an item is decrease  overtime
# this value can be overridden in the bank-data.yml file for a specific item
# default value = 0.01
overtime_price_drop: 0.01

# time interval at which the task to check item's price is ran
# if the time difference between the current time and the last time an item was bought is higher than (time_diff_drop)
# it's value will drop on every interval
# this value is also in minutes
# this value can not be overridden by a specific items for programmatic purpose
# default value = 720 (12 hours)
overtime_drop_interval: 720

# list of items that cannot be sold or bought through the bank system
blacklisted:
  - BEDROCK
  - WATER
  - FLOWING_WATER
  - AIR
  - LAVA
  - FLOWING_LAVA
  - LONG_GRASS
  - 'LONG_GRASS:1'
  - 'LONG_GRASS:2'
  - DEAD_BUSH
  - PISTON_HEAD
  - FIRE
  - MOB_SPAWNER
  - REDSTONE_WIRE
  - WHEAT
  - FARMLAND
  - LIT_FURNACE
  - STANDING_SIGN
  - WALL_SIGN
  - WOODEN_DOOR
  - IRON_DOOR
  - UNLIT_REDSTONE_TORCH
  - SNOW_LAYER
  - PORTAL
  - UNPOWERED_REPEATER
  - MONSTER_EGG
  - 'MONSTER_EGG:1'
  - 'MONSTER_EGG:2'
  - 'MONSTER_EGG:3'
  - 'MONSTER_EGG:4'
  - 'MONSTER_EGG:5'
  - PUMPKIN_STEM
  - MELON_STEM
  - END_PORTAL
  - END_PORTAL_FRAME
  - LIT_REDSTONE_LAMP
  - WOOD_DOUBLE_STEP
  - 'WOOD_DOUBLE_STEP:1'
  - 'WOOD_DOUBLE_STEP:2'
  - 'WOOD_DOUBLE_STEP:3'
  - 'WOOD_DOUBLE_STEP:4'
  - 'WOOD_DOUBLE_STEP:5'
  - COCOA
  - CARROTS
  - POTATOES
  - 'ANVIL:1'
  - 'ANVIL:2'
  - UNPOWERED_COMPARATOR
  - POWERED_COMPARATOR
  - BARRIER
  - STANDING_BANNER
  - WALL_BANNER
  - ENCHANTED_BOOK
  - WRITTEN_BOOK
  - BED_BLOCK
  - PISTON_EXTENSION
  - PISTON_MOVING_PIECE
  - CROPS
  - SOIL
  - BURNING_FURNACE
  - SIGN_POST
  - IRON_DOOR_BLOCK
  - GLOWING_REDSTONE_ORE
  - REDSTONE_TORCH_ON
  - BREWING_STAND
  - CAULDRON
  - ENDER_PORTAL
  - ENDER_PORTAL_FRAME
  - REDSTONE_LAMP_ON
  - COMMAND
  - FLOWER_POT
  - CARROT
  - POTATO
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - STANDING_BANNER
  - WALL_BANNER
  - DOUBLE_STONE_SLAB2
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - COMMAND_MINECART
  - SKULL
  - FIREBALL
  - NETHER_STALK
  - MAP
  - STRUCTURE_BLOCK
  - TIPPED_ARROW
  - SPLASH_POTION
  - LINGERING_POTION
  - BEETROOT_BLOCK
  - GRASS_PATH
  - MAGMA
  - NETHER_BRICK
  - STRUCTURE_VOID
  - SUGAR_CANE_BLOCK
  - COMMAND_CHAIN
  - COMMAND_REPEATING
  - FROSTED_ICE
  - END_GATEWAY
  - CAKE_BLOCK
  - DIODE_BLOCK_ON
  - DIODE_BLOCK_OFF
  - THE_BUTCHER
  - EXCALIBUR
  - OP
  - LEGOLAS_BOW
 
  